#!/usr/bin/env python3
"""Remove only conda-declared, unhashed generated Python bytecode.

Conda records noarch Python bytecode as ``path_type=pyc_file`` without a
content digest.  Micromamba may materialize those files while inspecting a
fresh prefix even when package linking uses ``--no-pyc``.  The authoritative
prefix audit deliberately requires these nondeterministic files to be absent.
This normalizer removes only paths declared as ``pyc_file`` whose source is a
package-owned regular ``.py`` file; every other prefix byte remains untouched
for the subsequent fail-closed archive audit.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import re
import stat
import sys
from typing import Any


PYC_PATTERN = re.compile(
    r"(.+)/__pycache__/([^/]+)\.cpython-([0-9]+)(?:\.opt-[0-9]+)?\.pyc\Z"
)


def canonical_directory(path: pathlib.Path, label: str) -> pathlib.Path:
    lexical = pathlib.Path(os.path.abspath(os.fspath(path)))
    try:
        info = lexical.lstat()
        resolved = lexical.resolve(strict=True)
    except OSError as error:
        raise RuntimeError(f"{label} is absent: {lexical}") from error
    if not stat.S_ISDIR(info.st_mode) or resolved != lexical:
        raise RuntimeError(f"{label} is not a canonical directory: {lexical}")
    return lexical


def canonical_regular(path: pathlib.Path, label: str) -> pathlib.Path:
    lexical = pathlib.Path(os.path.abspath(os.fspath(path)))
    try:
        info = lexical.lstat()
        resolved = lexical.resolve(strict=True)
    except OSError as error:
        raise RuntimeError(f"{label} is absent: {lexical}") from error
    if not stat.S_ISREG(info.st_mode) or resolved != lexical:
        raise RuntimeError(f"{label} is not a canonical regular file: {lexical}")
    return lexical


def safe_relative(value: Any) -> str:
    if not isinstance(value, str):
        raise RuntimeError("conda package path record is invalid")
    relative = pathlib.PurePosixPath(value)
    if relative.is_absolute() or not relative.parts or ".." in relative.parts:
        raise RuntimeError("conda package path escapes the environment prefix")
    text = relative.as_posix()
    if text in {"", "."} or text.startswith("./"):
        raise RuntimeError("conda package path is not canonical")
    return text


def fingerprint(info: os.stat_result) -> tuple[int, ...]:
    return (
        info.st_dev,
        info.st_ino,
        info.st_mode,
        info.st_uid,
        info.st_gid,
        info.st_size,
        info.st_mtime_ns,
        info.st_ctime_ns,
    )


def remove_regular(path: pathlib.Path) -> tuple[int, str]:
    parent = canonical_directory(path.parent, "generated bytecode parent")
    parent_flags = os.O_RDONLY | os.O_CLOEXEC
    if hasattr(os, "O_DIRECTORY"):
        parent_flags |= os.O_DIRECTORY
    if hasattr(os, "O_NOFOLLOW"):
        parent_flags |= os.O_NOFOLLOW
    file_flags = os.O_RDONLY | os.O_CLOEXEC
    if hasattr(os, "O_NOFOLLOW"):
        file_flags |= os.O_NOFOLLOW
    parent_descriptor = os.open(parent, parent_flags)
    try:
        descriptor = os.open(path.name, file_flags, dir_fd=parent_descriptor)
        try:
            initial = os.fstat(descriptor)
            if not stat.S_ISREG(initial.st_mode):
                raise RuntimeError(f"generated bytecode is not regular: {path}")
            digest = hashlib.sha256()
            size = 0
            while True:
                block = os.read(descriptor, 1024 * 1024)
                if not block:
                    break
                digest.update(block)
                size += len(block)
            current = os.stat(
                path.name, dir_fd=parent_descriptor, follow_symlinks=False
            )
            if fingerprint(current) != fingerprint(initial):
                raise RuntimeError(f"generated bytecode changed before removal: {path}")
            os.unlink(path.name, dir_fd=parent_descriptor)
            try:
                os.stat(path.name, dir_fd=parent_descriptor, follow_symlinks=False)
            except FileNotFoundError:
                pass
            else:
                raise RuntimeError(f"generated bytecode survived removal: {path}")
            return size, digest.hexdigest()
        finally:
            os.close(descriptor)
    finally:
        os.close(parent_descriptor)


def normalize(prefix: pathlib.Path) -> dict[str, Any]:
    prefix = canonical_directory(prefix, "conda prefix")
    metadata_directory = canonical_directory(prefix / "conda-meta", "conda metadata")
    metadata_files = sorted(metadata_directory.glob("*.json"))
    if not metadata_files:
        raise RuntimeError("conda metadata package set is empty")

    owned: dict[str, str] = {}
    generated: list[str] = []
    for metadata_path in metadata_files:
        metadata_path = canonical_regular(metadata_path, "conda metadata")
        try:
            metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError) as error:
            raise RuntimeError(f"invalid conda metadata: {metadata_path.name}") from error
        paths = metadata.get("paths_data", {}).get("paths")
        if not isinstance(paths, list):
            raise RuntimeError(f"conda paths metadata is absent: {metadata_path.name}")
        for record in paths:
            if not isinstance(record, dict):
                raise RuntimeError("conda package path record is invalid")
            relative = safe_relative(record.get("_path"))
            path_type = record.get("path_type")
            if relative in owned:
                raise RuntimeError(f"conda package path has duplicate owners: {relative}")
            if not isinstance(path_type, str):
                raise RuntimeError(f"conda package path type is invalid: {relative}")
            owned[relative] = path_type
            if path_type == "pyc_file":
                generated.append(relative)

    removed: list[dict[str, Any]] = []
    absent = 0
    for relative in sorted(generated):
        match = PYC_PATTERN.fullmatch(relative)
        if match is None:
            raise RuntimeError(
                f"generated bytecode path is not source-derived: {relative}"
            )
        source_relative = f"{match.group(1)}/{match.group(2)}.py"
        if owned.get(source_relative) != "hardlink":
            raise RuntimeError(
                f"generated bytecode source is not package-owned: {relative}"
            )
        source = prefix / source_relative
        canonical_regular(source, "generated bytecode source")
        target = prefix / relative
        try:
            target_info = target.lstat()
        except FileNotFoundError:
            absent += 1
            continue
        if not stat.S_ISREG(target_info.st_mode) or target.resolve(strict=True) != target:
            raise RuntimeError(f"generated bytecode is not a canonical file: {relative}")
        size, digest = remove_regular(target)
        removed.append({"path": relative, "size_bytes": size, "sha256": digest})

    remaining = [relative for relative in generated if (prefix / relative).exists()]
    if remaining:
        raise RuntimeError(
            "declared generated bytecode remains after normalization: " + remaining[0]
        )
    return {
        "schema_version": 1,
        "environment_prefix": str(prefix),
        "metadata_package_count": len(metadata_files),
        "declared_generated_bytecode_path_count": len(generated),
        "already_absent_path_count": absent,
        "removed_path_count": len(removed),
        "removed": removed,
        "pass": True,
    }


def write_report(path: pathlib.Path, report: dict[str, Any]) -> None:
    destination = pathlib.Path(os.path.abspath(os.fspath(path)))
    parent = canonical_directory(destination.parent, "normalization report parent")
    if destination.exists() or destination.is_symlink():
        raise RuntimeError(f"normalization report already exists: {destination}")
    temporary = parent / f".{destination.name}.tmp.{os.getpid()}"
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC
    descriptor = os.open(temporary, flags, 0o600)
    try:
        payload = (json.dumps(report, indent=2, sort_keys=True) + "\n").encode("utf-8")
        offset = 0
        while offset < len(payload):
            offset += os.write(descriptor, payload[offset:])
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
    try:
        os.replace(temporary, destination)
    except BaseException:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass
        raise


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prefix", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    try:
        write_report(args.output, normalize(args.prefix))
    except (OSError, RuntimeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
